In [6]:
%pip install pandas
import pandas as pd

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: pandas in c:\python312\lib\site-packages (2.2.3)




[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
movies = pd.read_csv('dataset.csv')
movies.head()

id                        title                 genre original_language  \
0    278     The Shawshank Redemption           Drama,Crime                en   
1  19404  Dilwale Dulhania Le Jayenge  Comedy,Drama,Romance                hi   
2    238                The Godfather           Drama,Crime                en   
3    424             Schindler's List     Drama,History,War                en   
4    240       The Godfather: Part II           Drama,Crime                en   

                                            overview  popularity release_date  \
0  Framed in the 1940s for the double murder of h...      94.075   1994-09-23   
1  Raj is a rich, carefree, happy-go-lucky second...      25.408   1995-10-19   
2  Spanning the years 1945 to 1955, a chronicle o...      90.585   1972-03-14   
3  The true story of how businessman Oskar Schind...      44.761   1993-12-15   
4  In the continuing saga of the Corleone crime f...      57.749   1974-12-20   

   vote_average  vote_count  
0           8.7       21862  
1           8.7        3731  
2           8.7       16280  
3           8.6       12959  
4           8.6        9811

### Choose some columns I think users will rely on more: Feature Selection

In [15]:
movies = movies[['id','title','overview', 'genre', ]]
movies.head()

id                        title  \
0    278     The Shawshank Redemption   
1  19404  Dilwale Dulhania Le Jayenge   
2    238                The Godfather   
3    424             Schindler's List   
4    240       The Godfather: Part II   

                                            overview                 genre  
0  Framed in the 1940s for the double murder of h...           Drama,Crime  
1  Raj is a rich, carefree, happy-go-lucky second...  Comedy,Drama,Romance  
2  Spanning the years 1945 to 1955, a chronicle o...           Drama,Crime  
3  The true story of how businessman Oskar Schind...     Drama,History,War  
4  In the continuing saga of the Corleone crime f...           Drama,Crime

In [16]:
movies['tags'] = movies['overview'] + movies['genre']
movies.head()

id                        title  \
0    278     The Shawshank Redemption   
1  19404  Dilwale Dulhania Le Jayenge   
2    238                The Godfather   
3    424             Schindler's List   
4    240       The Godfather: Part II   

                                            overview                 genre  \
0  Framed in the 1940s for the double murder of h...           Drama,Crime   
1  Raj is a rich, carefree, happy-go-lucky second...  Comedy,Drama,Romance   
2  Spanning the years 1945 to 1955, a chronicle o...           Drama,Crime   
3  The true story of how businessman Oskar Schind...     Drama,History,War   
4  In the continuing saga of the Corleone crime f...           Drama,Crime   

                                                tags  
0  Framed in the 1940s for the double murder of h...  
1  Raj is a rich, carefree, happy-go-lucky second...  
2  Spanning the years 1945 to 1955, a chronicle o...  
3  The true story of how businessman Oskar Schind...  
4  In the continuing saga of the Corleone crime f...

In [17]:
new_data = movies.drop(columns=['overview', 'genre'])
new_data.head()

id                        title  \
0    278     The Shawshank Redemption   
1  19404  Dilwale Dulhania Le Jayenge   
2    238                The Godfather   
3    424             Schindler's List   
4    240       The Godfather: Part II   

                                                tags  
0  Framed in the 1940s for the double murder of h...  
1  Raj is a rich, carefree, happy-go-lucky second...  
2  Spanning the years 1945 to 1955, a chronicle o...  
3  The true story of how businessman Oskar Schind...  
4  In the continuing saga of the Corleone crime f...

In [18]:
%pip install scikit-learn
from sklearn.feature_extraction.text import CountVectorizer

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
cv = CountVectorizer(max_features=10000, stop_words='english')
vector = cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

In [20]:
vector.shape

(10000, 10000)

In [21]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(10000, 10000))

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

In [24]:
similarity = cosine_similarity(vector)
similarity

array([[1.        , 0.05634362, 0.13041013, ..., 0.07559289, 0.11065667,
        0.06900656],
       [0.05634362, 1.        , 0.07715167, ..., 0.        , 0.03636965,
        0.        ],
       [0.13041013, 0.07715167, 1.        , ..., 0.02300219, 0.0673435 ,
        0.09449112],
       ...,
       [0.07559289, 0.        , 0.02300219, ..., 1.        , 0.03253   ,
        0.03042903],
       [0.11065667, 0.03636965, 0.0673435 , ..., 0.03253   , 1.        ,
        0.04454354],
       [0.06900656, 0.        , 0.09449112, ..., 0.03042903, 0.04454354,
        1.        ]], shape=(10000, 10000))

### now access the index

In [26]:
new_data[new_data['title'] == "The Godfather"].index[0].item()

2

In [39]:
enumerated_list = list(enumerate(similarity[2]))
cleaned_list = [(index, float(value)) for index, value in enumerated_list]


In [40]:
distance = sorted(cleaned_list, reverse=True, key=lambda vector:vector[1])
for i in distance[0:5]:
    print(new_data.iloc[i[0]].title)

The Godfather
The Godfather: Part II
Blood Ties
Joker
Bomb City


In [43]:
import numpy as np

def recommend(movies):
    index = new_data[new_data['title'] == movies].index[0]
    
    # Enumerate and clean the similarity list
    enumerated_list = list(enumerate(similarity[index]))
    cleaned_list = [(index, float(value)) for index, value in enumerated_list]
    
    distance = sorted(cleaned_list, reverse=True, key=lambda vector: vector[1])
    
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

In [44]:
recommend("Iron Man")

Iron Man
Iron Man 3
Guardians of the Galaxy Vol. 2
Avengers: Age of Ultron
Star Wars: Episode III - Revenge of the Sith


In [45]:
import pickle

In [46]:
pickle.dump(new_data, open('movies_list.pkl', 'wb'))

In [52]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [53]:
pickle.load(open('similarity.pkl', 'rb'))

array([[1.        , 0.05634362, 0.13041013, ..., 0.07559289, 0.11065667,
        0.06900656],
       [0.05634362, 1.        , 0.07715167, ..., 0.        , 0.03636965,
        0.        ],
       [0.13041013, 0.07715167, 1.        , ..., 0.02300219, 0.0673435 ,
        0.09449112],
       ...,
       [0.07559289, 0.        , 0.02300219, ..., 1.        , 0.03253   ,
        0.03042903],
       [0.11065667, 0.03636965, 0.0673435 , ..., 0.03253   , 1.        ,
        0.04454354],
       [0.06900656, 0.        , 0.09449112, ..., 0.03042903, 0.04454354,
        1.        ]], shape=(10000, 10000))